apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv-helm
  labels:
    type: local
  deletionGracePeriodSeconds: 0
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/jenkins-vol-helm"