---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment-helm
  labels:
    app: web-helm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-helm
  template:
    metadata:
      labels:
        app: web-helm
    spec:
      containers:
        - name: web
          image: salomirao/pythonapp-web
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: web-helm
spec:
  ports:
  - port: 5000
    protocol: TCP
    name: web-helm
  selector:
    app: web-helm
  type: LoadBalancer